// See https://svelte.dev/docs/kit/types#app.d.ts
// for information about these interfaces
declare global {
	// Augments the global `Env` interface generated by `wrangler types`
	// (worker-configuration.d.ts, gitignored). Secrets must come from
	// Pages environment variables / .dev.vars — never from the repository.
	interface Env {
		SESSION_SECRET: string;
		PASSWORD_HASH: string;
	}

	namespace App {
		interface Platform {
			env: Env;
			ctx: ExecutionContext;
			caches: CacheStorage;
			cf?: IncomingRequestCfProperties;
		}

		// interface Error {}
		// interface Locals {}
		// interface PageData {}
		// interface PageState {}
	}
}

export {};
